version: "3.3"
services:
  backend:
    image: tachyonic/gothello:server-41ee5e7
    restart: unless-stopped

  client:
    image: tachyonic/gothello:client-3f4bf16
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
